name: Test with Report

on:
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  linter:
    name: Ruff linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check .
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Upload tests report
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
  report:
    name: Generate allure report
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - name: Generate allure report
        run: allure generate -c allure-results -o allure-report --clean
      - name: Upload allure to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: allure-report
      - name: Deploy allure report
        id: deployment
        uses: actions/deploy-pages@v1.2.9